plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
}
architectury { minecraft = project.minecraft_version }
allprojects { group = rootProject.maven_group; version = rootProject.mod_version }
subprojects {
    apply plugin: 'dev.architectury.loom'; apply plugin: 'architectury-plugin'; apply plugin: 'maven-publish'
    repositories { mavenCentral(); maven { url = 'https://maven.neoforged.net/releases' };
        maven { url = 'https://maven.fabricmc.net/' };
        maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' } }
    dependencies { minecraft "net.minecraft:minecraft:$rootProject.minecraft_version";
        mappings loom.officialMojangMappings() }
 java { toolchain.languageVersion = JavaLanguageVersion.of(21); withSourcesJar() }
 tasks.withType(JavaCompile).configureEach { options.release = 21 }
    def artifactVersion = "${rootProject.mod_version}-${rootProject.minecraft_version}"
    tasks.named('jar') {
        archiveBaseName = rootProject.archives_name
        archiveVersion = artifactVersion
        archiveClassifier = project.name
    }
    tasks.named('sourcesJar') {
        archiveBaseName = rootProject.archives_name
        archiveVersion = artifactVersion
        archiveClassifier = "${project.name}-sources"
    }
    tasks.named('remapJar') {
        archiveBaseName = rootProject.archives_name
        archiveVersion = artifactVersion
        archiveClassifier = project.name
        doFirst { archiveClassifier.set(project.name) }
    }
    tasks.named('remapSourcesJar') {
        archiveBaseName = rootProject.archives_name
        archiveVersion = artifactVersion
        archiveClassifier = "${project.name}-sources"
        doFirst { archiveClassifier.set("${project.name}-sources") }
    }
}

tasks.register('genIntellijRuns') { dependsOn(':fabric:genIntellijRuns', ':neoforge:genIntellijRuns') }
