modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0-only"

[[mods]]
modId = "neoguanniao"
version = "2.9.1"
logoFile = "icon.png"
displayName = "Neo Guan Niao"
displayURL = "https://space.bilibili.com/38982471"
authors = "Fodoth_jinzi89, EdDYON"

description = '''Unofficial 1.21.1 Neoforge version of Guaniao'''

[[mixins]]
config = "neoguanniao.mixins.json"

[[dependencies."neoguanniao"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."neoguanniao"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies."neoguanniao"]]
modId = "geckolib"
type = "required"
versionRange = "[4.4,)"
ordering = "NONE"
side = "BOTH"